#version: '3.8'
#
services:
  users-api:
    build:
      context: ./backend/users-api/
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: users-api-boot.jar
    environment:
      SPRING_PROFILES_ACTIVE: local
      DATASOURCE_URL: jdbc:postgresql://db:5432/usersdb
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Optional: expose for external DB tools
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  integration-tests:
    build:
      context: ./collections
      dockerfile: src/main/docker/Dockerfile
    environment:
      COLLECTION: users-api
      ENV: dev
    depends_on:
      - users-api
    volumes:
      - tests:/app/tests/results
    networks:
      - app-network


volumes:
  pgdata:
  tests:

networks:
  app-network:
    driver: bridge
