---
spring:
  application:
    name: "users-api"
  datasource:
    url: "jdbc:h2:mem:usersdb"
    username: "sa"
    password: null
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    defer-datasource-initialization: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: "/h2-console"
springdoc:
  api-docs:
    path: "/api-docs"
management:
  endpoints:
    web:
      exposure:
        include: "health"
