---
spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: null
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
springdoc:
  api-docs:
    path: "/api-docs"
