name: Setup Java and Maven
description: Checkout, setup JDK and Maven settings

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
    - uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: '[{"id": "ghcr.io", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
