name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: write
  packages: read

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-maven

      - name: Spotless
        run: mvn spotless:check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-maven

      - name: Build and Test
        run: mvn -B verify
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  dependency-graph:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-maven
      - uses: advanced-security/maven-dependency-submission-action@v5
